// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    // "aws_cognito_identity_pool_id": "us-east-1:3aa9bad7-77b0-4fd6-b273-fe8f62bfb1cc",
    // "aws_cognito_region": "us-east-1",
    // "aws_user_pools_id": "us-east-1_xKPVL7Kc4",
    // "aws_user_pools_web_client_id": "2lb3gg6sq0s1dlutvj2jtu9nis",
    "oauth": {}
};


export default awsmobile;
